spring:
  application:
    name: microservice-simple-consumer-movie

server:
  port: 8010

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

